Django_Blog/Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path as url 
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about, name='about'),
    url(r'^$', views.index, name='index'),
    url('articles/', include('articles.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Blog/Blog/accounts/urls.py
from django.urls import path
from django.urls import re_path as url 
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

Django_Blog/Blog/articles/urls.py
from django.urls import path
from django.urls import re_path as url 
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.articles_list, name='list'),
    url(r'create/$', views.article_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name='detail'),
]

Django_Blog/Blog/accounts/models.py
from django.db import models

# Create your models here.

Django_Blog/Blog/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title, self.author
    
    def snippet(self):
        return self.body[:50] + '...'

Django_Blog/Blog/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

Django_Blog/Blog/Blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')
    

Django_Blog/Blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log user in
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('index')

Django_Blog/Blog/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms


# Create your views here.
def articles_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/articles_list.html', {'articles': articles})

def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

Django_Blog/Blog/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next%}
            <input type="hidden" name="next" value="{{ request.GET.next }}"></input>
        {% endif %}
        <input type="submit" name="" value="Login">
    </form>
{% endblock %}

Django_Blog/Blog/accounts/templates/accounts/signup.html
{% extends "base.html"%}
{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" name="" value="Signup">
    </form>
{% endblock %}

Django_Blog/Blog/articles/templates/articles/article_create.html
{% extends "base.html" %}
{% block content %}
    <div class="create-article">
        <h2>Create a new article</h2>
        <form class="site-form" method="post" action="{% url 'articles:create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Post article">
        </form>
    </div>
{% endblock %}

Django_Blog/Blog/articles/templates/articles/article_detail.html
{% extends "base.html" %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <img class="thumb" src="{{ article.thumb.url }}">
        <p>{{ article.date }}</p>
    </div>
</div>

{% endblock %}

Django_Blog/Blog/articles/templates/articles/articles_list.html
{% extends "base.html" %}
{% block content %}
<h1>Articles List</h1>
<div class="articles">
    {% for article in articles %}
        <div class="article">
            <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
            <p>{{ article.snippet }}</p>
            <p>{{ article.date }}</p>
        </div>
    {% endfor %}
</div>
{% endblock %}

Django_Blog/Blog/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>About me and this project.</h1>
<p>I'm an authodidact that learns everything that can in his free time. I'm currently working as hard as I can with my resources to become a full-time web developer.<br>
This is a proof of that. Please take in consideration to tell me what I can improve inside this particular project or any other that I made.<br>
Thank you.</p>
{% endblock %}

Django_Blog/Blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Python for dummies - Blog</title>
    <meta name="description" content="A brief description">
    <meta name="author" content="your Site name">

    <!-- Open Graph Protocol-->
    
    <meta property="og:title" content="A brief description">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.mysite">
    <meta property="og:description" content="A description">
    <meta property="og:image" content="image.png">
    
    <link rel="icon" href="/favicon.ico">
    <link rel="icon" href="/favicon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@300&display=swap');
        body h1, h2, p{
            font-family: 'Hanken Grotesk', sans-serif;
            font-size: 250%%;
        }
    </style>
    
    <!-- Include your CSS file here -->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <!-- <link rel="stylesheet" href="css/styles.css"> -->
    </head>
<body>
    <!--Refresh with CTRL + F5-->
    <div class="nav">
        <nav>
            <!-- Add your website navigation here -->
            <>
                <li class="btn">
                    <a href="{% url 'index' %}">Homepage</a>
                </li>
                <li class="btn">
                    <a href="{% url 'articles:list' %}">Articles</a>
                </li>
                <li class="btn">
                    <a href="{% url 'about' %}">About</a>
                </li>
                {% if user.is_authenticated %}
                <li class="btn">
                    <a href="{% url 'articles:create' %}">New article</a>
                </li>
                <li class="btn">
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="subtmit">Logout</button>
                    </form>
                </li>
                {% else %}
                <li class="btn log">
                    <a href="{% url 'accounts:login' %}">Login</a>
                    <a href="{% url 'accounts:signup' %}">Signup</a>
                </li>
                {% endif %}
        </nav>
    </div>
    <header class='title'>
        <!-- Add your website name or logo here -->
        <p>Python for dummies - Blog</p>
    </header>
    <main>
        {% block content %}
        <!-- Add your main content here -->
        <h1>Heading</h1>
        {% endblock %}
    </main>
    <br>
    <footer>
        <!-- Add copyright notices and other footer content here -->
        <p>Sebastian Lapalma © 2023 - Argentina</p>
    </footer>
</body>
</html>

Django_Blog/Blog/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome to my blog</h1>
<p>This a blog made using Django.<br>Contrary to what you may initially believe, this is not a tutorial. This is a blog I developed just to practice my abilities with this framework.</p>
{% endblock %}